import type { VendorTransaction } from './schema'

export const MOCK_TRANSACTIONS: VendorTransaction[] = [
  {
    id: '1',
    transactionType: 'Purchase',
    representing: 'Buyer',
    address: '20547 South Avalon Blvd, Carson, CA',
    owner: 'Dennis Cid',
    ownerAvatar: 'https://i.pravatar.cc/150?u=dennis',
    lender: '1781 - Alex Padilla',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Fidelity National',
    tcCompany: 'SBTC',
    titleCompany: 'Other',
    closingDate: '2026-01-15',
  },
  {
    id: '2',
    transactionType: 'Lease Listing',
    representing: 'Tenant',
    address: '10111 Long Beach Blvd, Lynwood, CA',
    owner: 'Javier Alvarez',
    ownerAvatar: 'https://i.pravatar.cc/150?u=javier',
    lender: 'CASH',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Other',
    tcCompany: 'Alvarez',
    titleCompany: 'Orange Coast',
    closingDate: '2026-01-22',
  },
  {
    id: '3',
    transactionType: 'Listing',
    representing: 'Seller',
    address: '73550 Cabazon Peak Dr, Palm Desert, CA',
    owner: 'Kristina Massaro',
    lender: 'Other',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Other',
    tcCompany: 'Maria',
    titleCompany: 'Fidelity - Stearns',
    closingDate: '2026-02-01',
  },
  {
    id: '4',
    transactionType: 'Lease',
    representing: 'Buyer',
    address: '356 W 90th St, Los Angeles, CA',
    owner: 'Monserrat Torres',
    ownerAvatar: 'https://i.pravatar.cc/150?u=monse',
    lender: 'Other',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Other',
    tcCompany: 'Conci',
    titleCompany: 'Other',
    closingDate: '2026-02-14',
  },
  {
    id: '5',
    transactionType: 'Listing',
    representing: 'Seller',
    address: '2518 Pearson Ave, Pomona, CA',
    owner: 'Scott Kato',
    lender: 'N/A - Listing',
    escrowCompany: 'Simply Escrow - Linda',
    homeWarranty: 'Old Republic H...',
    tcCompany: 'SBTC',
    titleCompany: 'Fidelity National',
    closingDate: '2026-02-28',
  },
  {
    id: '6',
    transactionType: 'Lease',
    representing: 'Buyer',
    address: '26 Middleton Ct, Pomona, CA',
    owner: 'Victoria Posth',
    ownerAvatar: 'https://i.pravatar.cc/150?u=victoria',
    lender: 'Other',
    escrowCompany: 'Other - Cardinal',
    homeWarranty: 'Other',
    tcCompany: 'na',
    titleCompany: 'Other',
    closingDate: '2026-03-05',
  },
  {
    id: '7',
    transactionType: 'Listing',
    representing: 'Seller',
    address: '5912 San Remo Dr, Buena Park, CA',
    owner: 'Brandon Lee',
    lender: 'N/A - Listing',
    escrowCompany: 'Simply Escrow - Sarah',
    homeWarranty: 'Waived in RPA',
    tcCompany: 'Diana',
    titleCompany: 'Fidelity National',
    closingDate: '2026-03-10',
  },
  {
    id: '8',
    transactionType: 'Referral',
    representing: 'Seller',
    address: '325 W 3rd St #1204, Los Angeles, CA',
    owner: 'Frances Escano',
    ownerAvatar: 'https://i.pravatar.cc/150?u=frances',
    lender: 'Credit Union',
    escrowCompany: 'Simply Escrow - Sarah',
    homeWarranty: 'Waived in RPA',
    tcCompany: 'Diana',
    titleCompany: 'Orange Coast',
    closingDate: '2026-03-18',
  },
  {
    id: '9',
    transactionType: 'Purchase',
    representing: 'Tenant',
    address: '18403 Devlin Ave, Artesia, CA',
    owner: 'Isayas Theodros',
    lender: 'Other',
    escrowCompany: 'Simply Escrow - Sarah',
    homeWarranty: 'Other',
    tcCompany: 'SBTC',
    titleCompany: 'Other',
    closingDate: '2026-03-22',
  },
  {
    id: '10',
    transactionType: 'Listing',
    representing: 'Seller',
    address: '16628 Victor St, Lakewood, CA',
    owner: 'Marina Hong',
    ownerAvatar: 'https://i.pravatar.cc/150?u=marina',
    lender: 'Other',
    escrowCompany: 'Simply Escrow - Sarah',
    homeWarranty: 'Other',
    tcCompany: 'Meiko',
    titleCompany: 'Other',
    closingDate: '2026-03-29',
  },
  {
    id: '11',
    transactionType: 'Purchase',
    representing: 'Buyer',
    address: '1812 E Cyrene Dr, Carson, CA',
    owner: 'Other',
    lender: 'Other',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Choice',
    tcCompany: 'Confi',
    titleCompany: 'Other',
    closingDate: '2026-04-01',
  },
  {
    id: '12',
    transactionType: 'Lease',
    representing: 'Buyer',
    address: '6324 Quebec Dr, Los Angeles, CA',
    owner: 'Aaron Reyes',
    ownerAvatar: 'https://i.pravatar.cc/150?u=aaron',
    lender: 'Other',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'N/A',
    tcCompany: 'Other',
    titleCompany: 'Other',
    closingDate: '2026-04-05',
  },
  {
    id: '13',
    transactionType: 'Purchase',
    representing: 'Buyer',
    address: '28390 Blackjack Rd, Canyon Country, CA',
    owner: 'Adam Loria',
    lender: 'Other',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Other',
    tcCompany: 'Coast',
    titleCompany: 'Other',
    closingDate: '2026-04-07',
  },
  {
    id: '14',
    transactionType: 'Listing',
    representing: 'Seller',
    address: '20849 Jamison St, Canoga Park, CA',
    owner: 'Adam Loria',
    ownerAvatar: 'https://i.pravatar.cc/150?u=adam',
    lender: 'Other',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Fidelity National',
    tcCompany: 'Cris So',
    titleCompany: 'Other',
    closingDate: '2026-04-08',
  },
  {
    id: '15',
    transactionType: 'Purchase',
    representing: 'Referral',
    address: '226 W Maitan Ave, Monterey Park, CA',
    owner: 'Adam Loria',
    lender: 'Other',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Other',
    tcCompany: 'Coast',
    titleCompany: 'Other',
    closingDate: '2026-04-09',
  },
  {
    id: '16',
    transactionType: 'Listing',
    representing: 'Landlord',
    address: '1461 Goldeneast St, Diamond Bar, CA',
    owner: 'Visakha Sir',
    ownerAvatar: 'https://i.pravatar.cc/150?u=visakha',
    lender: 'Other',
    escrowCompany: 'Simply Escrow - Sarah',
    homeWarranty: 'First American',
    tcCompany: 'Sothy',
    titleCompany: 'Other',
    closingDate: '2026-04-09',
  },
  {
    id: '17',
    transactionType: 'Referral',
    representing: 'Referral',
    address: '4262 Mesa Vista Dr, Hacienda Heights, CA',
    owner: 'Xavier Zaragoza',
    lender: 'N/A - Listing',
    escrowCompany: 'Simply Escrow - Sarah',
    homeWarranty: 'Fidelity National',
    tcCompany: 'Erin L',
    titleCompany: 'Other',
    closingDate: '2026-04-09',
  },
  {
    id: '18',
    transactionType: 'Purchase',
    representing: 'Referral',
    address: '645 Chestnut Ave, Long Beach, CA',
    owner: 'Xavier Zaragoza',
    ownerAvatar: 'https://i.pravatar.cc/150?u=xavier',
    lender: 'Other',
    escrowCompany: 'Simply Escrow - Sarah',
    homeWarranty: 'First American',
    tcCompany: 'Erin',
    titleCompany: 'Other',
    closingDate: '2026-04-09',
  },
  {
    id: '19',
    transactionType: 'Lease Listing',
    representing: 'Landlord',
    address: '1031 N Lilac Ave, Rialto, CA',
    owner: 'Adam Loria',
    lender: 'Other',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Other',
    tcCompany: 'N/A',
    titleCompany: 'Other',
    closingDate: '2026-04-09',
  },
  {
    id: '20',
    transactionType: 'Referral',
    representing: 'Referral',
    address: '29217 Walker Ave, Murrieta, CA',
    owner: 'Adam Loria',
    lender: 'Other',
    escrowCompany: 'Other - Not Listed',
    homeWarranty: 'Other',
    tcCompany: 'Coast',
    titleCompany: 'Other',
    closingDate: '2026-04-09',
  },
]
